name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run
      run: |
        git submodule init
        git submodule update

        sh ./scripts/build
        sh ./scripts/run
